[phases.setup]
nixPkgs = ['python311', 'postgresql']

[phases.install]
cmds = [
  'python -m venv --copies /opt/venv',
  '. /opt/venv/bin/activate && pip install --upgrade pip',
  '. /opt/venv/bin/activate && pip install --no-cache-dir -r requirements.txt'
]

[phases.build]
cmds = ['echo "No build phase needed"']

[start]
cmd = 'uvicorn app.main:app --host 0.0.0.0 --port $PORT'
